### ISSUE TITLE
Sidecar unable to connect to xenon follower

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain-api#348]
After launching a sidecar configured to connect to a Xenon follower, it results in the following error in the sidecar logs:
```
{"message":"Warning: failed to connect to node RPC server at stacks-node-follower.prod-xenon.svc.cluster.local:20443","level":"error","timestamp":"2020-11-23T20:26:27.881Z"}
{"message":"Warning: failed to connect to node RPC server at stacks-node-follower.prod-xenon.svc.cluster.local:20443","level":"error","timestamp":"2020-11-23T20:27:03.242Z"}
{"message":"Warning: failed to connect to node RPC server at stacks-node-follower.prod-xenon.svc.cluster.local:20443","level":"error","timestamp":"2020-11-23T20:27:38.586Z"}
```

Corresponding logs from the follower:
```
{"msg":"HTTP: Have 0 peers now (max 1000) inbound=true, including 0 from host of 172.25.4.60:55348","level":"DEBG","ts":"2020-11-23T20:28:47.384429096+00:00","thread":"ThreadId(4)","line":210,"file":"src/net/server.rs"}
{"msg":"Registered HTTP TcpStream { addr: 172.25.10.42:20443, peer: 172.25.4.60:55348, fd: 50 } as event 729 (outbound=None)","level":"DEBG","ts":"2020-11-23T20:28:47.384535121+00:00","thread":"ThreadId(4)","line":266,"file":"src/net/server.rs"}
{"msg":"Socket deregistered: 729, TcpStream { addr: 172.25.10.42:20443, peer: 172.25.4.60:55348, fd: 50 } (Events total: 2, max: 800)","level":"DEBG","ts":"2020-11-23T20:28:47.390029416+00:00","thread":"ThreadId(4)","line":266,"file":"src/net/poll.rs"}
{"msg":"HTTP: Have 0 peers now (max 1000) inbound=true, including 0 from host of 172.25.4.60:55360","level":"DEBG","ts":"2020-11-23T20:28:48.394322857+00:00","thread":"ThreadId(4)","line":210,"file":"src/net/server.rs"}
{"msg":"Registered HTTP TcpStream { addr: 172.25.10.42:20443, peer: 172.25.4.60:55360, fd: 51 } as event 730 (outbound=None)","level":"DEBG","ts":"2020-11-23T20:28:48.394435763+00:00","thread":"ThreadId(4)","line":266,"file":"src/net/server.rs"}
{"msg":"Socket deregistered: 730, TcpStream { addr: 172.25.10.42:20443, peer: 172.25.4.60:55360, fd: 51 } (Events total: 2, max: 800)","level":"DEBG","ts":"2020-11-23T20:28:48.399043800+00:00","thread":"ThreadId(4)","line":266,"file":"src/net/poll.rs"}
```

I've confirmed from inside the sidecar pod that it _does_ have network connectivity to the follower:
```
curl stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/info
{"peer_version":385875968,"pox_consensus":"8b7fb38e04e72749d45b35b2912ba67bff9f2198","burn_block_height":1894408,"stable_pox_consensus":"74545cec981720aed9c6edc26d180ea92c4d7738","stable_burn_block_height":1894401,"server_version":"blockstack-core 0.0.1 => 23.0.0.0 (fix/xenon-fixes:131346a+, release build, linux [x86_64])","network_id":2147483648,"parent_network_id":118034699,"stacks_tip_height":0,"stacks_tip":"0000000000000000000000000000000000000000000000000000000000000000","stacks_tip_consensus_hash":"0000000000000000000000000000000000000000","unanchored_tip":"4ec7ae4a471502547f69ff7165ce5eab0257def1a6607770512fb66e5fcc7e79","exit_at_block_height":null}
```

**To Reproduce**
1. Talk to DevOps if needed

**Expected behavior**
The sidecar should be able to connect to the follower without error assuming they're both up.

**Additional context**
Sidecar version: `0.33.0`
Follower version: https://github.com/blockstack/stacks-blockchain/tree/fix/xenon-fixes

**Comment by zone117x** [comment]
This appears to be an issue with the follower node not being able to sync any Stacks blocks. Reproducible when running the stacks-node locally as a xenon follower, without any sidecar/event-observer attached. 

* stacks-node from latest [fix/xenon-fixes branch](https://github.com/blockstack/stacks-blockchain/commits/fix/xenon-fixes) branch at commit f0baf47
* Using config:
```toml
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@xenon.blockstack.org:20444"
prometheus_bind = "0.0.0.0:9153"
[burnchain]
chain = "bitcoin"
mode = "xenon"
peer_host = "bitcoind.xenon.blockstack.org"
username = "blockstack"
password = "blockstacksystem"
rpc_port = 18332
peer_port = 18333
[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000
[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000
```

It takes several minutes to sync the bitcoin testnet headers. Afterwards, the `stacks_tip_height` at my local `/v2/info` endpoint never goes past 0. For reference, the latest at http://xenon.blockstack.org:20443/v2/info is `194` and appears to be increasing as expected. There are no explicit error messages in the logs.

The `Warning: failed to connect to node RPC server...` messages from the sidecar are transient errors from the stacks-node http server randomly being unresponsive to pings against the `/v2/info` endpoint.
