### ISSUE TITLE
API client references not generated from latest sources

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#632]
The API client seems to miss methods for endpoints in the OpenAPI spec

**Comment by agraebe** [comment]
yeah, I just briefly compared the [api ref](https://blockstack.github.io/stacks-blockchain-api/) and the [client ref](https://blockstack.github.io/stacks-blockchain-api/client/index.html) and I cannot find:
- `/v2/prices` should result in a PricesApi class
- `/v2/namespaces` should result in a NamespacesApi class
- `/v2/names` should result in a NamesApi class
- I cannot fin a method to query the [`nft_events` endpoint](https://blockstack.github.io/stacks-blockchain-api/#operation/get_account_inbound)

There is likely more if we look closer. I wonder if the reason for the delta is the build & release process? Maybe the client generation isn't happening with each change?

**Comment by zone117x** [comment]
The functions for those endpoints can be found if you grep for them in the client source. In the case for those, they are:
```ts
const bnsApi = new BnsApi();
await bnsApi.getNamePrice({ name: 'test' });
await bnsApi.getAllNamespaces();
const accountsApi = new AccountsApi();
await accountsApi.getAccountNft({ principal: 'STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6' });
```

The container class name comes from the `tags` in `openapi.yaml`, e.g.:
```
  /v2/prices/namespaces/{tld}:
    get:
      tags:
        - bns
```

That's why it's `BnsApi` rather than `PricesApi`. 

Similarly, the `nft_events` endpoint is also just poorly named in the openapi.yaml:
```
  /extended/v1/address/{principal}/nft_events:
    get:
      summary: Get nft events
      description: |
        Get list of all nfts owned by an address, contains the clarity value of the identifier of the nft
      tags:
        - Accounts
      operationId: get_account_nft
```

I'd say this issue is more appropriately titled "better naming in openapi.yaml". I don't yet see any missing functions or indication that the client isn't being generated from the latest source.
